# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170619_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='button',
            old_name='document',
            new_name='audio',
        ),
        migrations.AddField(
            model_name='button',
            name='color',
            field=models.CharField(default='#00ff00', max_length=7),
        ),
        migrations.AlterField(
            model_name='button',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
