# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170629_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AudioFile'),
        ),
        migrations.AlterField(
            model_name='button',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
