# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170629_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pad',
            name='buttonlist',
        ),
        migrations.AddField(
            model_name='pad',
            name='buttonlist',
            field=models.ManyToManyField(to='accounts.Button'),
        ),
    ]
