# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_pad_preset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pad',
            name='preset',
        ),
        migrations.AddField(
            model_name='button',
            name='preset',
            field=models.CharField(choices=[('preset_reset', 0), ('preset_player', 1), ('preset_overlap', 2), ('preset_replay', 3)], default='preset_reset', max_length=15),
        ),
    ]
