# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170630_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='preset',
            field=models.CharField(choices=[('preset_reset', 1), ('preset_player', 1), ('preset_overlap', 2), ('preset_replay', 3)], default=0, max_length=2),
        ),
    ]
